version: '3.4'
services: 
  flaskapp: 
    build: 
      context: .
      dockerfile: ./sde/Dockerfile
    ports: 
      - "8000:8000"
    network_mode: host

  nginx: 
    build:
      context: .
      dockerfile: ./sde/Dockerfile./nginx/Dockerfile
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always
    network_mode: host